// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idsbyfkddemkjluehszi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkc2J5ZmtkZGVta2psdWVoc3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTU0MTgsImV4cCI6MjA3NDU3MTQxOH0.3dAWwdH2FbmiQbxcp6nC8XjtoSbOo7P0GU8wwJuPGDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});